name: surgeon-py36-tf23-gpu

dependencies:
  - python<3.7
  - pip
  - matplotlib
  - opencv
  - cudnn=7
  - cudatoolkit
  - pip:
    - tensorflow-gpu==2.3
    - numpy<=1.19.5
    - opencv-python>=4.0
    - keras
    - lxml
    - tqdm
